# Prediction
FIRA 빅데이터 플랫폼 과정 <데이터마이닝> - 2017.08.18.금 09:00-13:00

### 1. Data
- 1-1. `german_predictions.csv`
- 1-2. Preprocessing : dummy variables
- 1-3. Train-Test Split : `sklearn.model_selection.test_train_split`

### 2. Linear Regression
- 2-1. `sklearn.linear_model.LinearRegression`
- 2-2. Evaluation Measure 'RMS' : `sklearn.metrics.mean_squared_error`

### 3. k-nn
- 3-1. `sklearn.neighbors.KNeighborsRegressor`
- 3-2. Evaluation Measure 'RMS' : `sklearn.metrics.mean_squared_error`

### 4. SVM
- 4-1. `sklearn.svm.LinearSVR`
- 4-2. Evaluation Measure 'RMS' : `sklearn.metrics.mean_squared_error`

### 5. Cross-Validation Test
- 5-1. 필요성
- 5-2. K-Fold Cross Validation : `sklearn.cross_validation.cross_val_score`

### 6. 실습 : 신용 금액 예측 모델

### 1. Data
---

#### 1-1.  `german_predictions.csv`
---
`german_predictions.csv`는 독일 은행에 신용거래를 신청한 신청자 1000명의 데이터이다. 관찰번호(OBS#)를 제외하고 총 28개의 변수로 이루어져있으며, 각 신청자들의 '신용 금액(AMOUNT)'가 예측하고자 하는 변수이다.

In [3]:
import pandas as pd

In [4]:
# 변수별 설명 : CodeList
pd.read_csv('CodeList_predictions.csv').iloc[:, :4]

,변수명,설명,변수 종류,코드 설명
0,OBS#,관찰번호,-,일련번호
1,CHK_ACCT,당좌 예금 계좌 상태,범주형,"0 : 0 DM 미만, 1 : 0~200 DM 미만, 2 : 200 DM 이상, 3..."
2,DURATION,신용거래 개월 수,수치형,NaN
3,HISTORY,신용기록,범주형,"0 : 신용거래 없음, 1 : 기한 내 변제, 2 : 변제 기한 남음, 3 : 연체..."
4,NEW_CAR,신용목적,이진수형,신형 자동차 0 : 없음 1 : 있음
5,USED_CAR,신용목적,이진수형,중고 자동차 0 : 없음 1 : 있음
6,FURNITURE,신용목적,이진수형,가구/주방기기 0 : 없음 1 : 있음
7,RADIO/TV,신용목적,이진수형,라디오/TV 0 : 없음 1 : 있음
8,EDUCATION,신용목적,이진수형,교육 0 : 없음 1 : 있음
9,RETAINING,신용목적,이진수형,재교육 0 : 없음 1 : 있음
10,SAV_ACCT,보통예금 계좌 평균 잔고,범주형,"0 : 100 DM 미만, 1 : 100~500 DM, 2 : 500~1000 D..."
11,EMPLOYMENT,현 직장 재직 기간,범주형,"0 : 무직, 1 : 1년 미만, 2 : 1~4년 미만, 3 : 4~7년 미만, 4..."
12,INSTALL_RATE,가처분 소득 대비 할부금 이자율,수치형,NaN
13,MALE_DIV,이혼 남성,이진수형,"0 : 아니오, 1: 예"
14,MALE_SINGLE,미혼 남성,이진수형,"0 : 아니오, 1: 예"
15,MALE_MAR_WID,기혼 남성 혹은 홀아비,이진수형,"0 : 아니오, 1: 예"
16,CO-APPLICANT,공동 신청자,이진수형,"0 : 아니오, 1: 예"
17,GUARANTOR,보증인 유/무,이진수형,"0 : 아니오, 1: 예"
18,PRESENT_RESIDENT,현 주소지 거주 기간,범주형,NaN
19,REAL_ESTATE,부동산 보유,이진수형,"0 : 아니오, 1: 예"
20,PROP_UNKN_NONE,보유재산 없음,이진수형,"0 : 아니오, 1: 예"
21,AGE,연령,수치형,NaN
22,OTHER_INSTALL,타 할부 거래,이진수형,"0 : 아니오, 1: 예"
23,RENT,임대,이진수형,"0 : 아니오, 1: 예"
24,OWN_RES,주택 유/무,이진수형,"0 : 아니오, 1: 예"
25,NUM_CREDITS,현재 대출 건수,수치형,NaN
26,JOB,직종,범주형,"0 : 무직/비숙련 비정규직, 1 : 비숙련 정규직, 2 : 숙련직/작업감독, 3..."
27,NUM_DEPENDENTS,부양가족 수,수치형,NaN
28,TELEPHONE,전화 가입,이진수형,"0 : 아니오, 1: 예"
29,FOREIGN,외국인 근로자,이진수형,"0 : 아니오, 1: 예"
30,AMOUNT,신용금액,수치형,NaN

In [5]:
# df
df = pd.read_csv('german_predictions.csv').set_index('OBS#')
df

,CHK_ACCT,DURATION,HISTORY,NEW_CAR,USED_CAR,FURNITURE,RADIO/TV,EDUCATION,RETAINING,SAV_ACCT,...,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,JOB,NUM_DEPENDENTS,TELEPHONE,FOREIGN,AMOUNT
OBS#,,,,,,,,,,,,,,,,,,,,,
0,0,6,4,0,0,0,1,0,0,4,...,67,0,0,1,2,2,1,1,0,1169
1,1,48,2,0,0,0,1,0,0,0,...,22,0,0,1,1,2,1,0,0,5951
2,3,12,4,0,0,0,0,1,0,0,...,49,0,0,1,1,1,2,0,0,2096
3,0,42,2,0,0,1,0,0,0,0,...,45,0,0,0,1,2,2,0,0,7882
4,0,24,3,1,0,0,0,0,0,0,...,53,0,0,0,2,2,2,0,0,4870
5,3,36,2,0,0,0,0,1,0,4,...,35,0,0,0,1,1,2,1,0,9055
6,3,24,2,0,0,1,0,0,0,2,...,53,0,0,1,1,2,1,0,0,2835
7,1,36,2,0,1,0,0,0,0,0,...,35,0,1,0,1,3,1,1,0,6948
8,3,12,2,0,0,0,1,0,0,3,...,61,0,0,1,1,1,1,0,0,3059
9,1,30,4,1,0,0,0,0,0,0,...,28,0,0,1,2,3,1,0,0,5234
10,1,12,2,1,0,0,0,0,0,0,...,25,0,1,0,1,2,1,0,0,1295
11,0,48,2,0,0,0,0,0,0,0,...,24,0,1,0,1,2,1,0,0,4308
12,1,12,2,0,0,0,1,0,0,0,...,22,0,0,1,1,2,1,1,0,1567
13,0,24,4,1,0,0,0,0,0,0,...,60,0,0,1,2,1,1,0,0,1199
14,0,15,2,1,0,0,0,0,0,0,...,28,0,1,0,1,2,1,0,0,1403
15,0,24,2,0,0,0,1,0,0,1,...,32,0,0,1,1,1,1,0,0,1282
16,3,24,4,0,0,0,1,0,0,4,...,53,0,0,1,2,2,1,0,0,2424
17,0,30,0,0,0,0,0,0,0,4,...,25,1,0,1,3,2,1,0,0,8072
18,1,24,2,0,1,0,0,0,0,0,...,44,0,0,0,1,3,1,1,0,12579
19,3,24,2,0,0,0,1,0,0,2,...,31,0,0,1,1,2,2,1,0,3430
20,3,9,4,1,0,0,0,0,0,0,...,48,0,0,1,3,2,1,1,0,2134
21,0,6,2,0,0,0,1,0,0,2,...,44,0,1,0,1,2,2,0,0,2647
22,0,10,4,1,0,0,0,0,0,0,...,48,0,1,0,2,1,2,0,1,2241
23,1,12,4,0,1,0,0,0,0,1,...,44,0,0,1,1,2,1,0,0,1804
24,3,10,4,0,0,1,0,0,0,4,...,26,0,0,1,2,2,1,0,1,2069
25,0,6,2,0,0,1,0,0,0,0,...,36,1,0,1,1,1,1,1,0,1374
26,3,6,0,0,0,0,1,0,0,0,...,39,0,0,1,1,1,1,0,0,426
27,2,12,1,0,0,0,1,0,0,3,...,42,0,1,0,2,2,1,0,0,409
28,1,7,2,0,0,0,1,0,0,0,...,34,0,0,1,1,2,1,0,0,2415
29,0,60,3,0,0,0,0,0,0,0,...,63,0,0,1,2,2,1,1,0,6836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,1,15,2,0,0,0,0,0,0,1,...,22,0,0,1,1,2,1,0,0,1514
971,3,24,2,1,0,0,0,0,0,0,...,43,0,0,1,1,1,2,0,0,7393
972,0,24,1,1,0,0,0,0,0,0,...,29,0,1,0,2,0,1,0,0,1193
973,0,60,2,0,0,0,0,0,0,0,...,36,0,1,0,1,2,1,0,0,7297
974,3,30,4,0,0,0,1,0,0,0,...,33,0,0,1,1,2,1,1,0,2831
975,2,24,2,0,0,0,1,0,0,2,...,57,0,0,1,1,1,1,0,0,1258
976,1,6,2,0,0,0,1,0,0,0,...,64,0,0,1,1,2,1,0,0,753
977,1,18,3,0,0,0,0,0,0,4,...,42,0,0,1,2,2,1,0,0,2427
978,3,24,3,1,0,0,0,0,0,0,...,47,0,0,1,2,1,2,0,0,2538
979,1,15,1,1,0,0,0,0,0,1,...,25,0,1,0,1,2,1,0,0,1264
980,1,30,4,0,0,1,0,0,0,0,...,49,0,0,1,1,2,1,0,0,8386
981,3,48,2,0,0,0,0,0,0,0,...,33,1,1,0,1,3,1,1,0,4844
982,2,21,2,1,0,0,0,0,0,1,...,28,1,0,1,1,3,1,1,0,2923
983,0,36,2,0,1,0,0,0,0,0,...,26,0,0,1,1,2,2,0,0,8229
984,3,24,4,0,0,1,0,0,0,0,...,30,0,0,1,2,1,1,0,0,2028
985,0,15,4,0,0,1,0,0,0,0,...,25,0,1,0,2,2,1,0,0,1433
986,2,42,0,0,0,0,0,0,0,0,...,33,0,0,1,2,2,1,0,0,6289
987,3,13,2,0,0,0,1,0,0,1,...,64,0,0,1,1,2,1,0,0,1409
988,0,24,2,0,1,0,0,0,0,0,...,29,0,0,0,1,3,1,1,0,6579
989,1,24,4,0,0,0,1,0,0,0,...,48,0,0,1,2,1,1,0,0,1743
990,3,12,4,0,0,0,0,1,0,4,...,37,0,0,1,2,1,2,0,0,3565
991,3,15,1,0,0,0,1,0,0,1,...,34,1,0,1,1,1,2,0,0,1569
992,0,18,2,0,0,0,1,0,0,4,...,23,0,1,0,2,1,1,0,0,1936
993,0,36,2,0,0,1,0,0,0,0,...,30,0,0,1,1,3,1,1,0,3959
994,3,12,2,1,0,0,0,0,0,4,...,50,0,0,1,1,2,1,1,0,2390
995,3,12,2,0,0,1,0,0,0,0,...,31,0,0,1,1,1,1,0,0,1736
996,0,30,2,0,1,0,0,0,0,0,...,40,0,0,1,1,3,1,1,0,3857
997,3,12,2,0,0,0,1,0,0,0,...,38,0,0,1,1,2,1,0,0,804
998,0,45,2,0,0,0,1,0,0,0,...,23,0,0,0,1,2,1,1,0,1845
999,1,45,4,0,1,0,0,0,0,1,...,27,0,0,1,1,2,1,0,0,4576

#### 1-2. Preprocessing : dummy variables

In [6]:
# dummy varaibles : preprocessed_df
cols = ['CHK_ACCT', 'HISTORY', 'SAV_ACCT', 'EMPLOYMENT', 'JOB']
preprocessed_df = pd.get_dummies(df, columns=cols)
preprocessed_df

,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO/TV,EDUCATION,RETAINING,INSTALL_RATE,MALE_DIV,MALE_SINGLE,...,SAV_ACCT_4,EMPLOYMENT_0,EMPLOYMENT_1,EMPLOYMENT_2,EMPLOYMENT_3,EMPLOYMENT_4,JOB_0,JOB_1,JOB_2,JOB_3
OBS#,,,,,,,,,,,,,,,,,,,,,
0,6,0,0,0,1,0,0,4,0,1,...,1,0,0,0,0,1,0,0,1,0
1,48,0,0,0,1,0,0,2,0,0,...,0,0,0,1,0,0,0,0,1,0
2,12,0,0,0,0,1,0,2,0,1,...,0,0,0,0,1,0,0,1,0,0
3,42,0,0,1,0,0,0,2,0,1,...,0,0,0,0,1,0,0,0,1,0
4,24,1,0,0,0,0,0,3,0,1,...,0,0,0,1,0,0,0,0,1,0
5,36,0,0,0,0,1,0,2,0,1,...,1,0,0,1,0,0,0,1,0,0
6,24,0,0,1,0,0,0,3,0,1,...,0,0,0,0,0,1,0,0,1,0
7,36,0,1,0,0,0,0,2,0,1,...,0,0,0,1,0,0,0,0,0,1
8,12,0,0,0,1,0,0,2,1,0,...,0,0,0,0,1,0,0,1,0,0
9,30,1,0,0,0,0,0,4,0,0,...,0,1,0,0,0,0,0,0,0,1
10,12,1,0,0,0,0,0,3,0,0,...,0,0,1,0,0,0,0,0,1,0
11,48,0,0,0,0,0,0,3,0,0,...,0,0,1,0,0,0,0,0,1,0
12,12,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
13,24,1,0,0,0,0,0,4,0,1,...,0,0,0,0,0,1,0,1,0,0
14,15,1,0,0,0,0,0,2,0,0,...,0,0,0,1,0,0,0,0,1,0
15,24,0,0,0,1,0,0,4,0,0,...,0,0,0,1,0,0,0,1,0,0
16,24,0,0,0,1,0,0,4,0,1,...,1,0,0,0,0,1,0,0,1,0
17,30,0,0,0,0,0,0,2,0,1,...,1,0,1,0,0,0,0,0,1,0
18,24,0,1,0,0,0,0,4,0,0,...,0,0,0,0,0,1,0,0,0,1
19,24,0,0,0,1,0,0,3,0,1,...,0,0,0,0,0,1,0,0,1,0
20,9,1,0,0,0,0,0,4,0,1,...,0,0,0,1,0,0,0,0,1,0
21,6,0,0,0,1,0,0,2,0,1,...,0,0,0,1,0,0,0,0,1,0
22,10,1,0,0,0,0,0,1,0,1,...,0,0,1,0,0,0,0,1,0,0
23,12,0,1,0,0,0,0,3,0,1,...,0,0,1,0,0,0,0,0,1,0
24,10,0,0,1,0,0,0,2,0,0,...,1,0,0,1,0,0,0,0,1,0
25,6,0,0,1,0,0,0,1,0,1,...,0,0,0,1,0,0,0,1,0,0
26,6,0,0,0,1,0,0,4,0,0,...,0,0,0,0,0,1,0,1,0,0
27,12,0,0,0,1,0,0,3,0,0,...,0,0,0,1,0,0,0,0,1,0
28,7,0,0,0,1,0,0,3,0,1,...,0,0,0,1,0,0,0,0,1,0
29,60,0,0,0,0,0,0,3,0,1,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,15,0,0,0,0,0,0,4,0,1,...,0,0,0,1,0,0,0,0,1,0
971,24,1,0,0,0,0,0,1,0,1,...,0,0,0,1,0,0,0,1,0,0
972,24,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
973,60,0,0,0,0,0,0,4,0,1,...,0,0,0,0,0,1,0,0,1,0
974,30,0,0,0,1,0,0,4,0,0,...,0,0,0,1,0,0,0,0,1,0
975,24,0,0,0,1,0,0,3,0,0,...,0,0,0,1,0,0,0,1,0,0
976,6,0,0,0,1,0,0,2,0,0,...,0,0,0,1,0,0,0,0,1,0
977,18,0,0,0,0,0,0,4,0,1,...,1,0,0,0,0,1,0,0,1,0
978,24,1,0,0,0,0,0,4,0,1,...,0,0,0,0,0,1,0,1,0,0
979,15,1,0,0,0,0,0,2,0,0,...,0,0,0,1,0,0,0,0,1,0
980,30,0,0,1,0,0,0,2,0,1,...,0,0,0,0,1,0,0,0,1,0
981,48,0,0,0,0,0,0,3,0,1,...,0,1,0,0,0,0,0,0,0,1
982,21,1,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
983,36,0,1,0,0,0,0,2,0,1,...,0,0,0,1,0,0,0,0,1,0
984,24,0,0,1,0,0,0,2,0,1,...,0,0,0,0,1,0,0,1,0,0
985,15,0,0,1,0,0,0,4,0,0,...,0,0,0,1,0,0,0,0,1,0
986,42,0,0,0,0,0,0,2,1,0,...,0,0,1,0,0,0,0,0,1,0
987,13,0,0,0,1,0,0,2,0,0,...,0,1,0,0,0,0,0,0,1,0
988,24,0,1,0,0,0,0,4,0,1,...,0,1,0,0,0,0,0,0,0,1
989,24,0,0,0,1,0,0,4,0,1,...,0,0,0,0,0,1,0,1,0,0
990,12,0,0,0,0,1,0,2,0,1,...,1,0,1,0,0,0,0,1,0,0
991,15,0,0,0,1,0,0,4,0,1,...,0,0,0,0,0,1,0,1,0,0
992,18,0,0,0,1,0,0,2,0,0,...,1,0,0,0,1,0,0,1,0,0
993,36,0,0,1,0,0,0,4,0,1,...,0,1,0,0,0,0,0,0,0,1
994,12,1,0,0,0,0,0,4,0,1,...,1,0,0,0,0,1,0,0,1,0
995,12,0,0,1,0,0,0,3,0,0,...,0,0,0,0,1,0,0,1,0,0
996,30,0,1,0,0,0,0,4,1,0,...,0,0,0,1,0,0,0,0,0,1
997,12,0,0,0,1,0,0,4,0,1,...,0,0,0,0,0,1,0,0,1,0
998,45,0,0,0,1,0,0,4,0,1,...,0,0,0,1,0,0,0,0,1,0
999,45,0,1,0,0,0,0,3,0,1,...,0,1,0,0,0,0,0,0,1,0

In [7]:
# split X, y
X, y = preprocessed_df.drop('AMOUNT', axis=1), preprocessed_df.AMOUNT

#### 1-3. Train-Test Split : `sklearn.model_selection.train_test_split`
---
지도학습을 위해 주어진 데이터를 train set과 test set으로 나눈다.

In [8]:
# import packages
from sklearn.model_selection import train_test_split

In [10]:
# train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
X_train

,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO/TV,EDUCATION,RETAINING,INSTALL_RATE,MALE_DIV,MALE_SINGLE,...,SAV_ACCT_4,EMPLOYMENT_0,EMPLOYMENT_1,EMPLOYMENT_2,EMPLOYMENT_3,EMPLOYMENT_4,JOB_0,JOB_1,JOB_2,JOB_3
OBS#,,,,,,,,,,,,,,,,,,,,,
909,9,1,0,0,0,0,0,1,0,0,...,1,0,0,1,0,0,0,1,0,0
381,18,0,1,0,0,0,0,3,0,0,...,0,1,0,0,0,0,0,0,0,1
949,24,0,0,0,1,0,0,2,0,1,...,0,0,0,0,0,1,0,0,1,0
708,9,0,0,0,1,0,0,4,0,0,...,0,0,0,0,0,1,0,0,1,0
843,24,0,0,0,0,0,0,4,0,1,...,0,0,0,0,1,0,0,0,1,0
778,36,0,1,0,0,0,0,4,0,1,...,0,0,0,0,0,1,0,0,0,1
954,12,1,0,0,0,0,0,4,0,0,...,0,0,0,1,0,0,0,0,1,0
30,18,0,0,0,0,0,0,3,0,0,...,0,0,1,0,0,0,0,0,1,0
548,12,0,0,0,1,0,0,4,0,0,...,0,0,0,1,0,0,0,1,0,0
93,24,0,0,1,0,0,0,4,0,1,...,1,0,0,0,0,1,0,0,1,0
964,6,0,0,0,0,0,0,3,0,0,...,0,0,1,0,0,0,0,1,0,0
728,48,0,0,0,0,0,0,4,0,0,...,0,0,0,0,0,1,0,0,1,0
318,12,0,0,0,0,1,0,4,0,1,...,0,0,0,1,0,0,0,0,1,0
303,10,1,0,0,0,0,0,4,0,1,...,0,0,0,0,1,0,0,0,1,0
761,18,0,0,1,0,0,0,4,0,0,...,0,0,0,1,0,0,0,0,1,0
478,12,0,0,0,0,0,0,3,0,1,...,0,0,0,0,1,0,0,1,0,0
586,9,1,0,0,0,0,0,2,0,1,...,0,0,0,1,0,0,0,0,1,0
71,7,0,0,0,1,0,0,4,0,1,...,1,0,0,0,0,1,0,1,0,0
270,18,1,0,0,0,0,0,4,0,1,...,1,0,0,0,1,0,0,0,1,0
697,12,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
698,18,0,0,0,1,0,0,4,0,1,...,0,0,0,1,0,0,0,0,1,0
501,36,0,1,0,0,0,0,2,0,1,...,0,0,0,0,0,1,0,0,1,0
17,30,0,0,0,0,0,0,2,0,1,...,1,0,1,0,0,0,0,0,1,0
11,48,0,0,0,0,0,0,3,0,0,...,0,0,1,0,0,0,0,0,1,0
789,40,0,0,0,0,1,0,4,0,1,...,0,0,0,1,0,0,0,0,1,0
42,18,0,0,0,0,0,0,2,0,1,...,0,0,0,1,0,0,0,1,0,0
669,30,0,0,0,1,0,0,4,0,1,...,0,0,0,0,0,1,0,0,1,0
968,42,0,0,0,1,0,0,2,0,0,...,1,0,0,0,1,0,0,0,1,0
485,6,1,0,0,0,0,0,4,0,1,...,0,1,0,0,0,0,0,0,0,1
37,18,0,0,0,1,0,0,4,0,1,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,24,0,0,1,0,0,0,1,0,0,...,1,0,0,1,0,0,0,1,0,0
382,22,1,0,0,0,0,0,4,0,0,...,1,0,0,0,1,0,0,0,1,0
748,21,0,1,0,0,0,0,1,0,1,...,1,0,0,1,0,0,0,0,1,0
922,9,0,0,0,1,0,0,3,0,0,...,0,0,1,0,0,0,0,0,1,0
359,30,0,0,1,0,0,0,4,0,0,...,0,0,0,0,1,0,0,0,1,0
399,24,0,0,0,1,0,0,4,0,0,...,0,0,0,1,0,0,0,1,0,0
506,15,0,1,0,0,0,0,2,0,1,...,0,0,0,1,0,0,0,0,1,0
803,12,0,0,0,1,0,0,4,0,1,...,1,0,0,0,0,1,0,0,1,0
633,9,0,0,1,0,0,0,2,0,0,...,0,0,1,0,0,0,0,0,1,0
221,12,0,0,0,0,1,0,4,0,0,...,1,0,0,1,0,0,0,0,1,0
390,18,1,0,0,0,0,0,2,0,0,...,0,0,0,1,0,0,0,0,0,1
239,30,0,0,0,1,0,0,1,0,1,...,0,0,0,0,0,1,0,0,1,0
574,9,0,0,0,1,0,0,4,0,1,...,0,0,0,0,0,1,0,1,0,0
466,24,0,0,0,1,0,0,4,0,0,...,0,0,1,0,0,0,0,1,0,0
167,11,0,0,1,0,0,0,4,0,0,...,0,0,1,0,0,0,0,0,1,0
678,24,0,0,0,1,0,0,4,0,1,...,0,0,0,0,0,1,0,1,0,0
395,39,0,0,0,0,1,0,2,0,1,...,0,0,0,0,1,0,0,0,1,0
904,24,0,0,0,1,0,0,4,0,1,...,0,0,0,0,0,1,0,0,0,1
682,15,0,0,0,1,0,0,4,0,0,...,0,0,0,1,0,0,0,0,1,0
939,24,0,1,0,0,0,0,2,0,1,...,1,0,0,1,0,0,0,0,0,1
426,28,0,0,0,1,0,0,4,0,1,...,0,0,0,0,0,1,0,0,1,0
626,6,0,0,1,0,0,0,2,0,1,...,0,0,0,1,0,0,0,0,1,0
487,24,1,0,0,0,0,0,4,0,0,...,0,0,0,0,0,1,0,0,1,0
174,21,0,0,0,0,1,0,2,0,1,...,0,0,1,0,0,0,0,0,1,0
599,24,0,0,0,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,1,0
813,48,0,0,0,0,0,0,3,0,1,...,0,0,0,1,0,0,0,0,1,0
746,15,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
714,60,1,0,0,0,0,0,4,0,1,...,0,0,0,0,1,0,0,0,0,1
57,36,0,0,0,1,0,0,2,0,0,...,0,0,0,1,0,0,0,0,1,0
357,36,0,0,0,1,0,0,4,0,1,...,0,0,0,1,0,0,0,0,0,1

In [26]:
# random_state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=23)

### 2. Linear Regression
---

#### 2-1. `sklearn.linear_model.LinearRegression`
---

In [27]:
# import packages
from sklearn.linear_model import LinearRegression

In [28]:
# Parameters
# fit_intercept = True # 상수를 넣을 것인지
# normalize = False # 변수들을 normalize한 상태로 모델을 얻을 것인지

In [29]:
# lr_model
lr_model = LinearRegression()

In [30]:
# fit to model
lr_model.fit(X=X_train, y=y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [32]:
# get predictions
y_pred_lr = lr_model.predict(X=X_test)

In [38]:
# result_y_test_df 
result_y_test_df = pd.DataFrame(y_test)
result_y_test_df['lr'] = y_pred_lr
result_y_test_df

      AMOUNT           lr
OBS#
519      700   494.091598
837      601  1596.477601
208     6568  3111.590480
525     7966  5437.910722
978     2538  2679.097113
583     2384  5228.838401
508     1413  1574.169316
158     3512  4578.534863
589     2246  2049.206111
201     1168   111.155696
280     3368  3913.900885
167     1577   404.137925
974     2831  3223.550695
95     15945  8948.136831
236    14555  2154.046600
203      902  -230.834214
790     1188  2892.136729
428     1313  2557.070204
998     1845  5665.824196
381    12976  4812.206868
705     5324  3067.683465
410     1967  2022.994469
684     9857  7098.577546
211     3835  5442.658530
585     2039  3238.698001
934     1498   192.261987
905     1107  3647.022826
883     1098   473.319620
844     3422  2277.676422
329     1068  -559.132122
...      ...          ...
196     1382  2713.699194
995     1736  1221.404150
345     1459   887.687721
59      6229  6266.557221
215      932  2506.008072
22      2241  3277.251236
26       426 -1007.501435
253     4151  4650.826428
157      339    52.142256
816     1338  2298.065147
655     3973  3514.113494
847     1249  1787.820315
729     1275  3826.858069
415     5842  6584.154213
733     2603  4623.917535
749     3029  3586.413700
955     1231  3674.556725
477     5152  1412.628346
919     3345  4184.198414
983     8229  6091.689402
734     3380  1563.341962
819     1345   410.578483
404     2899  1943.235594
860     5804  3173.223073
268     8978  5177.573675
689     3651  2967.312731
979     1264  2380.299519
161     1055  1817.830653
935     1919  5752.289064
502     1126   753.023110

[250 rows x 2 columns]

#### 2-2. Evaluation Measure 'RMS' : `sklearn.metrics.mean_squared_error`
---

In [41]:
# import packages
from sklearn.metrics import mean_squared_error
import math

In [44]:
# error_lr
# rms_lr
error_lr = mean_squared_error(y_pred=y_pred_lr, y_true=y_test)
rmse_lr = math.sqrt(error_lr)
rmse_lr

2109.358689622847

### 3. k-nn
---

#### 3-1. `sklearn.neighbors.KNeighborRegressor`
---

In [47]:
# import packages
from sklearn.neighbors import KNeighborsRegressor

In [48]:
# set parameters
n_neighbors = 5
# weights = 'uniform' # 주변 데이터의 가중치를 모두 동일하게, 'distance' 선택시, 거리에 반비례

In [49]:
# knn_model
knn_model = KNeighborsRegressor(n_neighbors=n_neighbors)

In [50]:
# fit to model
knn_model.fit(X=X_train, y=y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [52]:
# get predictions
y_pred_knn = knn_model.predict(X=X_test)

In [53]:
# result_y_test_df
result_y_test_df['knn'] = y_pred_knn
result_y_test_df

      AMOUNT           lr      knn
OBS#
519      700   494.091598   1104.4
837      601  1596.477601   1220.0
208     6568  3111.590480   2577.8
525     7966  5437.910722   5725.4
978     2538  2679.097113   3464.6
583     2384  5228.838401   4044.4
508     1413  1574.169316   2276.0
158     3512  4578.534863   5158.6
589     2246  2049.206111   1673.2
201     1168   111.155696   1152.8
280     3368  3913.900885   2187.2
167     1577   404.137925   1342.0
974     2831  3223.550695   3858.0
95     15945  8948.136831   8348.8
236    14555  2154.046600   1494.0
203      902  -230.834214    892.0
790     1188  2892.136729   2932.0
428     1313  2557.070204   1633.0
998     1845  5665.824196   6472.4
381    12976  4812.206868   3997.0
705     5324  3067.683465   1711.6
410     1967  2022.994469   2724.2
684     9857  7098.577546   6196.6
211     3835  5442.658530  11631.2
585     2039  3238.698001   2252.0
934     1498   192.261987   1864.6
905     1107  3647.022826   1271.0
883     1098   473.319620   1947.6
844     3422  2277.676422   1552.2
329     1068  -559.132122    967.4
...      ...          ...      ...
196     1382  2713.699194   1257.2
995     1736  1221.404150   1437.2
345     1459   887.687721   2235.6
59      6229  6266.557221   6053.2
215      932  2506.008072   1742.6
22      2241  3277.251236   1741.2
26       426 -1007.501435    744.6
253     4151  4650.826428   2890.6
157      339    52.142256   1574.2
816     1338  2298.065147   1349.4
655     3973  3514.113494   2102.4
847     1249  1787.820315   2196.8
729     1275  3826.858069   2659.8
415     5842  6584.154213   6016.2
733     2603  4623.917535   3583.8
749     3029  3586.413700   3406.4
955     1231  3674.556725   1343.4
477     5152  1412.628346   2436.8
919     3345  4184.198414   3104.0
983     8229  6091.689402   5035.2
734     3380  1563.341962   2100.4
819     1345   410.578483   1951.8
404     2899  1943.235594   3370.4
860     5804  3173.223073   3444.8
268     8978  5177.573675   2291.0
689     3651  2967.312731   1985.4
979     1264  2380.299519   1618.4
161     1055  1817.830653   1687.2
935     1919  5752.289064   4181.8
502     1126   753.023110   2213.6

[250 rows x 3 columns]

#### 3-2. Evaluation Measure 'RMS' : `sklearn.metrics.mean_squared_error`
---

In [15]:
# import packages

In [54]:
# error_knn
# rms_knn
error_knn = mean_squared_error(y_true=y_test, y_pred=y_pred_knn)
rmse_knn = math.sqrt(error_knn)
rmse_knn

2562.72025972403

### 4. SVM
---

#### 4-1. `sklearn.svm.LinearSVR`
---

In [55]:
# import packages
from sklearn.svm import LinearSVR

In [56]:
# set parameters
C=1.0 # soft margin 허용량

In [57]:
#svm_model
svm_model = LinearSVR(C=C)

In [59]:
# fit to model
svm_model.fit(X=X_train, y=y_train)

LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_intercept=True,
     intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
     random_state=None, tol=0.0001, verbose=0)

In [60]:
# get predictions
y_pred_svm = svm_model.predict(X=X_test)

In [61]:
# result_y_test_df
result_y_test_df['svm'] = y_pred_svm
result_y_test_df

      AMOUNT           lr      knn          svm
OBS#
519      700   494.091598   1104.4   590.221704
837      601  1596.477601   1220.0   756.542310
208     6568  3111.590480   2577.8  3007.691524
525     7966  5437.910722   5725.4  3531.803105
978     2538  2679.097113   3464.6  3108.991024
583     2384  5228.838401   4044.4  4434.500420
508     1413  1574.169316   2276.0  2720.623920
158     3512  4578.534863   5158.6  3392.468718
589     2246  2049.206111   1673.2  1928.936042
201     1168   111.155696   1152.8  1134.206656
280     3368  3913.900885   2187.2  1884.840307
167     1577   404.137925   1342.0   954.988542
974     2831  3223.550695   3858.0  3644.930522
95     15945  8948.136831   8348.8  7385.376524
236    14555  2154.046600   1494.0  1056.662342
203      902  -230.834214    892.0  1107.771671
790     1188  2892.136729   2932.0  2924.465512
428     1313  2557.070204   1633.0  1365.326624
998     1845  5665.824196   6472.4  5453.495980
381    12976  4812.206868   3997.0  2512.989671
705     5324  3067.683465   1711.6  2298.737722
410     1967  2022.994469   2724.2  2619.362685
684     9857  7098.577546   6196.6  5075.036858
211     3835  5442.658530  11631.2  4894.235091
585     2039  3238.698001   2252.0  2450.039040
934     1498   192.261987   1864.6  1084.024003
905     1107  3647.022826   1271.0  1592.903411
883     1098   473.319620   1947.6  2529.226867
844     3422  2277.676422   1552.2  2420.169932
329     1068  -559.132122    967.4   429.356951
...      ...          ...      ...          ...
196     1382  2713.699194   1257.2  1087.367934
995     1736  1221.404150   1437.2  1468.589836
345     1459   887.687721   2235.6  1794.850274
59      6229  6266.557221   6053.2  4371.388849
215      932  2506.008072   1742.6  1205.785485
22      2241  3277.251236   1741.2  1892.976631
26       426 -1007.501435    744.6   533.368224
253     4151  4650.826428   2890.6  3378.904283
157      339    52.142256   1574.2  1391.842078
816     1338  2298.065147   1349.4  1505.762810
655     3973  3514.113494   2102.4  2039.764886
847     1249  1787.820315   2196.8  2736.305417
729     1275  3826.858069   2659.8  3291.803958
415     5842  6584.154213   6016.2  4967.908840
733     2603  4623.917535   3583.8  3266.249126
749     3029  3586.413700   3406.4  2170.719568
955     1231  3674.556725   1343.4  3226.445779
477     5152  1412.628346   2436.8  2690.206848
919     3345  4184.198414   3104.0  3074.283810
983     8229  6091.689402   5035.2  4769.675438
734     3380  1563.341962   2100.4   934.246922
819     1345   410.578483   1951.8  1841.126123
404     2899  1943.235594   3370.4  2253.338827
860     5804  3173.223073   3444.8  2812.197957
268     8978  5177.573675   2291.0  2404.704508
689     3651  2967.312731   1985.4  1896.731613
979     1264  2380.299519   1618.4  1954.142666
161     1055  1817.830653   1687.2  2072.405131
935     1919  5752.289064   4181.8  3655.735267
502     1126   753.023110   2213.6  1416.624926

[250 rows x 4 columns]

#### 4-2. Evaluation Measure 'RMS' : `sklearn.metrics.mean_squared_error`
---

In [21]:
# import packages

In [62]:
# error_svm
# rms_svm
error_svm = mean_squared_error(y_pred=y_pred_svm, y_true=y_test)
rmse_svm = math.sqrt(error_svm)
rmse_svm

2459.3861848462125

### 5. Cross Validation Test
---
#### 5-1. 필요성
---

In [63]:
# train, test set을 바꿔보자
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X, y, test_size=0.25, random_state=17)

In [64]:
# 이미 학습한 모델로 새로운 test set의 prediction 값을 얻어보자
y_pred_new = lr_model.predict(X=X_test_new)

In [65]:
# rms
math.sqrt(mean_squared_error(y_pred=y_pred_new, y_true=y_test_new))

1956.1375817275464

#### 5-2.  K-Fold Cross Validation : `sklearn.cross_validation.cross_val_score`
---

In [66]:
# import packages
from sklearn.cross_validation import cross_val_score

In [68]:
# set parameters
estimator= lr_model
cv=5 # 전체 데이터를 k개의 그룹으로 나누고 총 k번의 모델 training - test를 반복한다.
       # 이 때 각 회차마다 test set이 되는 그룹을 계속 바꾼다.
scorer=rmse_scorer # Evaluation Measure로 사용할 Score Function - scorer(estimator, X, y)

In [67]:
def rmse_scorer(estimator, X, y):
    y_pred = estimator.predict(X=X)
    rmse = math.sqrt(mean_squared_error(y_pred=y_pred, y_true=y)) 
    return rmse

In [69]:
# cross_val_score
cross_val_score(estimator=estimator, cv=cv, scoring=scorer, X=X, y=y)

array([ 1837.64271999,  2070.5463413 ,  1465.1035543 ,  1748.82098496,
        2112.80639905])

In [28]:
# cv_test_result_df

In [29]:
# run cv test for more models & add cols to cv_test_result_df

### 6. 실습 : 신용 금액 예측 모델
---
전처리된 데이터를 이용하여 신용 금액을 가장 잘 예측하는 모델을 찾아라.
- 전처리를 더 수행해도 무방하다. 단, 전처리를 수행한 과정을 기술하라.
- 5개 이상의 모델을 비교하여라. (* 참고 : 같은 모델에 다른 parameter를 사용한 것도 다른 모델로 본다 *)
- cross validation test를 반드시 수행하고(cv=5 이상), 결과를 df로 저장하여라.
- 가장 좋은 모델을 고르고, 그 이유를 설명하여라.

##### (Optional) Preprocessing
---

##### Models
---

##### Cross-Validation Test
---

##### Best Model
---

은행에서 신용 금액 예측 모델을 도입하려고 할 때, 어떤 모델을 추천할 것인가?
- 가장 좋은 모델을 보여주는 것이 가장 좋은가? 
- 각 모델들의 장단점을 생각해보자.
- 은행에 모델들을 설명해야한다고 할 때 어떻게 설명할 것인가?
- 현업에 모델을 도입하려고 할 때 가장 먼저 고려해야하는 것이 무엇이라고 생각하는가?